import { mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { compile } from "json-schema-to-typescript"

const repositoryRoot = resolve(import.meta.dir, "..")
const schemaDirectory = resolve(repositoryRoot, Bun.argv[3] ?? "schemas/v1")
const outputPath = resolve(
  repositoryRoot,
  Bun.argv[2] ?? "plugins/opencode/src/generated/protocol.gen.ts",
)
const protocolSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Protocol",
  oneOf: [
    { $ref: "request.schema.json" },
    { $ref: "response.schema.json" },
    { $ref: "state.schema.json" },
  ],
  $defs: {
    exitClass: { $ref: "models.schema.json#/$defs/exitClass" },
  },
}
const exitClassSchema: Parameters<typeof compile>[0] = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "ExitClassContract",
  type: "object",
  additionalProperties: false,
  properties: {
    exit_class: { $ref: "models.schema.json#/$defs/exitClass" },
  },
  required: ["exit_class"],
}

const generationOptions = {
  $refOptions: {
    resolve: {
      http: false,
    },
  },
  additionalProperties: false,
  bannerComment: "// Code generated by json-schema-to-typescript v15.0.4. DO NOT EDIT.",
  cwd: schemaDirectory,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  ignoreMinAndMaxItems: false,
  inferStringEnumKeysFromValues: false,
  maxItems: 20,
  strictIndexSignatures: true,
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: false,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
  unknownAny: true,
  unreachableDefinitions: true,
} as const

const generated = await compile(protocolSchema, "Protocol", generationOptions)
const exitClassGenerated = await compile(exitClassSchema, "ExitClassContract", {
  ...generationOptions,
  bannerComment: "",
})

await mkdir(dirname(outputPath), { recursive: true })
await Bun.write(
  outputPath,
  `${generated.replaceAll("\r\n", "\n").trimEnd()}\n\n${exitClassGenerated.replaceAll("\r\n", "\n").trim()}\n`,
)
